### ISSUE TITLE
Error when running resnet18

### ISSUE THREAD

**Issue by yecheng-xiang** [elliothe/BFA#4]
When I was trying to perform the attacks on resnet18,  I modified the `model` in BFA_imagenet.sh to `resnet18`, and got the following errors:

```
Traceback (most recent call last):
  File "main.py", line 860, in <module>
    main()
  File "main.py", line 445, in main
    random_attack=args.random_bfa)
  File "main.py", line 592, in perform_attack
    attack_log = attacker.progressive_bit_search(model, data, target)
  File "/home/yecheng/repo/BFA/attack/BFA.py", line 124, in progressive_bit_search
    key=operator.itemgetter(1))[0]
ValueError: max() arg is an empty sequence
```

I also tried the other [Github repo](https://github.com/elliothe/Neural_Network_Weight_Attack) for your previous paper, however, the issue persists. 

May I get some help?

**Comment by yecheng-xiang** [comment]
Maybe I am getting it wrong, does this BFA framework support attacking float-point models? I was interested in attacking those mobilenet_v2 or resnet18 as they are without quantizing them.

**Comment by elliothe** [comment]
> Maybe I am getting it wrong, does this BFA framework support attacking float-point models? I was interested in attacking those mobilenet_v2 or resnet18 as they are without quantizing them.

No, it does not. You don't need any attacking algorithm for the floating model. Just simply change the exponent bit of random weight in the first layer, the attack will succeed.
